import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'firebase_options.dart';
import 'services/auth_service.dart';
import 'controller/auth_controller.dart';
import 'app_config.dart';

void main() async {
  // Ensure everything is ready before starting the app
  WidgetsFlutterBinding.ensureInitialized();
  
  // Connect to Firebase - uses platform-specific options generated by CLI
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Android-specific Google Sign-In init
  if (defaultTargetPlatform == TargetPlatform.android) {
    await GoogleSignIn.instance.initialize();
  }

  // Inject permanent services/controllers
  Get.put(AuthService(), permanent: true);
  Get.put(AuthController(), permanent: true);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final auth = Get.find<AuthService>();

    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Recipe App',
      
      // Global app theme configuration
      theme: ThemeData(
        useMaterial3: true,
        scaffoldBackgroundColor: AppColors.background,
        
        // Custom color scheme from our primary color
        colorScheme: ColorScheme.fromSeed(
          seedColor: AppColors.primary,
          surface: AppColors.appBar,
        ),
        
        // Making the AppBar look clean across all screens
        appBarTheme: const AppBarTheme(
          backgroundColor: AppColors.appBar,
          surfaceTintColor: Colors.transparent,
          scrolledUnderElevation: 0,
          elevation: 0,
          centerTitle: true,
          titleTextStyle: TextStyle(
            color: Colors.black87,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        
        // Consistent card styling
        cardTheme: const CardThemeData(
          color: AppColors.card,
          surfaceTintColor: Colors.transparent,
          elevation: 1.5,
          margin: EdgeInsets.symmetric(vertical: 4, horizontal: 8),
        ),
        
        textTheme: GoogleFonts.outfitTextTheme(),
      ),
      
      // Decide where to start based on auth state
      initialRoute: auth.isLoggedIn ? AppRoutes.home : AppRoutes.login,
      getPages: AppRoutes.pages,
    );
  }
}

